# Generated by Django 3.2.2 on 2021-08-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
