# Generated by Django 3.2.2 on 2021-06-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTopPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ImageField(upload_to='uploads/')),
                ('Bg_Colour', models.TextField()),
            ],
        ),
    ]
