# Generated by Django 3.2.2 on 2021-07-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagetoppost',
            name='title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
    ]
