# Generated by Django 3.2.2 on 2021-07-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_homepagetoppost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetoppost',
            name='upload',
            field=models.ImageField(upload_to='content/static/'),
        ),
    ]
