# Generated by Django 3.2.6 on 2021-08-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
