# Generated by Django 3.2.2 on 2021-07-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_homepagetoppost_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetoppost',
            name='upload',
            field=models.ImageField(blank=True, upload_to='static/content/'),
        ),
    ]
