# Generated by Django 3.2.6 on 2021-08-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_galleryimages_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='unit_name',
            field=models.TextField(default='Unit 1'),
        ),
    ]
