# Generated by Django 3.2.6 on 2021-08-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/content/'),
        ),
    ]
