# Generated by Django 3.2.2 on 2021-07-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_homepagetoppost_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagetoppost',
            name='link',
            field=models.URLField(default='http://www.bbc.co.uk'),
            preserve_default=False,
        ),
    ]
