# Generated by Django 3.2.2 on 2021-07-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_homepagetoppost_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetoppost',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
