# Generated by Django 3.2.6 on 2021-08-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='qual_name',
            field=models.TextField(default='GCSE'),
        ),
    ]
