# Generated by Django 3.2.2 on 2021-07-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_galleryimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='image',
            field=models.ImageField(upload_to='static/content/'),
        ),
    ]
