# Generated by Django 3.2.6 on 2021-08-19 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20210819_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='topic',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='content.topic'),
            preserve_default=False,
        ),
    ]
