# Generated by Django 3.2.6 on 2021-08-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_questionset_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
