# Generated by Django 3.2.6 on 2021-08-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_answer_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_set',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='content.questionset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tags',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.questionset'),
        ),
    ]
