# Generated by Django 3.2.6 on 2021-08-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
