# Generated by Django 3.2.6 on 2021-08-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_answer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='question',
            new_name='questionset',
        ),
    ]
